spring:
  datasource:
      url: jdbc:mysql://localhost:3306/test_schema
      username: root
      password: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
server:
  port: 8081

services:
  identity-service:
    url: http://localhost:8085/api/user
    authentication-type: Basic
    authentication-key: YWRtaW46cGFzc3dvcmQ=